name: asroo_store
description: "asroo store"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #language
  flutter_localizations:
    sdk: flutter

  # dart run build_runner build --delete-conflicting-outputs

  cupertino_icons: ^1.0.6
  #Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  # Core
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  get_it: ^7.7.0
  #UI Animation
  animate_do: ^3.3.2
  #Bloc
  flutter_bloc: ^8.1.3
  #shared preferences
  shared_preferences: ^2.2.2
  #freezed
  freezed_annotation: ^2.4.4
  #APi
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.6
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icons/play_store_512.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - lang/ar.json
    - lang/en.json
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - assets/images/icons/
    - assets/svg/


  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
